### ISSUE TITLE
Quarterly Payments are returning null response

### ISSUE THREAD

**Issue by joromecox** [goldwasserexchange/bond-calculator#74]
I am have a list of bonds and when the frequency is set to 4 for a couple of bonds the response is NaN. When used with Annual or Semi-Annual it works fine

```
{ 
maturity: 2025-01-15,
redemption: 100,
settlement: 2018-08-21,
frequency: 4,
rate: .0.07,
convention: '30U/360' 
}

yld = bond.yield(100);

```
![capture](https://user-images.githubusercontent.com/38970690/44438254-57181280-a58c-11e8-8b89-632cfaa1579c.PNG)
An Suggestions?

**Comment by jogold** [comment]
Hi @joromecox,

Thanks for bringing this up. It should be fixed in v0.1.8.
